//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnliceShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SlideImage
    {
        public int SlidId { get; set; }
        public string SlidTitle { get; set; }
        public string SlidImage { get; set; }
    }
}
